### ISSUE TITLE
restrict ?edit

### ISSUE THREAD

**Issue by ma-hack** [robromano/django-adminrestrict#1]
hi, can you please also include the ?edit to your access checks?

You need adjust the following line:

class AdminPagesRestrictMiddleware(object):
"""
A middleware that restricts login attempts to admin pages to
restricted IP addresses only. Everyone else gets 403.
"""

def process_request(self, request):
# Section adjusted to restrict login to ?edit (sing cms-toolbar-login)into DjangoCMS login.
if (request.path.startswith(reverse('admin:index')) or "cms-toolbar-login" in request.build_absolute_uri()) and request.method == 'POST':

Best regards,
Marco

**Comment by robromano** [comment]
Do you think you can do this and submit a pull request?
