### ISSUE TITLE
New version on Pypi?

### ISSUE THREAD

**Issue by primal100** [robromano/django-adminrestrict#20]
Would appreciate it! :)

**Comment by robromano** [comment]
Thanks for the ping. Will work on a new release soon.

**Comment by KristobalJunta** [comment]
Waiting for this release too, as my project depends on adminrestrict - and current PyPi version doesn't support ASGI v3 async middleware.
Please let me know if anything is blocking the release - I'm willing to help here.

**Comment by primal100** [comment]
Any update on this? :)

**Comment by robromano** [comment]
Pushed v3.1 to pypi - https://pypi.org/project/django-adminrestrict/3.1/

**Comment by robromano** [comment]
Sorry for the delay, will look into a new release soon.
