### ISSUE TITLE
Configure DEFAULT_AUTO_FIELD setting

### ISSUE THREAD

**Issue by KristobalJunta** [robromano/django-adminrestrict#23]
On Django 3.2 with latest adminrestrict version ([d39edd3](https://github.com/robromano/django-adminrestrict/commit/d39edd39f8ad284711949c5924fa1f5e41fd5ba5) for the time being) a warning is raised.

```
adminrestrict.AllowedIP: (models.W042) Auto-created primary key used when not defining a primary key type,
by default 'django.db.models.AutoField'. HINT: Configure the DEFAULT_AUTO_FIELD setting or the
AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```

AllowedIP uses AutoField - and future Django versions will use BigAutoField - thus the warning.
Details can be found [here](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys)

**Comment by robromano** [comment]
Thanks — if you have a PR for this and we can add Django 3.2 to the test
matrix to validate 3.2.
