### ISSUE TITLE
Cover all current Python and Django versions on Travis (build matrix)

### ISSUE THREAD

**Issue by bittner** [robromano/django-adminrestrict#6]
The current [build matrix](https://github.com/robromano/django-adminrestrict/blob/master/.travis.yml) on [Travis](https://travis-ci.org/robromano/django-adminrestrict) covers Python 2.7 and 3.3 with Django 1.4 to 1.7.

It would be nice to have all current Python/Django combinations covered (see [example](https://github.com/jcassee/django-analytical/blob/master/.travis.yml) using [Tox](https://github.com/jcassee/django-analytical/blob/master/tox.ini)).

**Comment by robromano** [comment]
I did this when adding support for Django 2.0/2.1
