### ISSUE TITLE
Upgrade to new Middleware (Django 1.10-style)

### ISSUE THREAD

**Issue by bittner** [robromano/django-adminrestrict#7]
A new style of middleware was introduced for use with the new MIDDLEWARE setting in Django 1.10. It's possible to upgrade the middleware to support both the old- and new-style middlewares (see [Django docs](https://docs.djangoproject.com/en/1.10/topics/http/middleware/)).

django-adminrestrict should support the new-style `MIDDLEWARE` setting.

See Also
----------
- [Upgrading pre-Django 1.10-style middleware](https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware)

**Comment by robromano** [comment]
This is done
